# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c01c11adf12a2f39233634cc019f88af9f4f33e08c8bf9553e10db7c480a4ca73f1488e5396c7b342e8673be0e53c25dc7d3ec758d94ea668cfce3d5cb105b7c

test:
  secret_key_base: 0d7ac13c9db022129c89c3f61100d52db393ba4990a8e31054075166eaca02afda7cf947961921f37f0ac170cc837eca683360f6a3dc2a1a51066345e36192f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
